site_name: 'user-api'
site_description: 'User API service documentation'

docs_dir: docs

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Authentication: authentication.md
  - Database Schema: database.md

plugins:
  - techdocs-core
