site_name: 'frontend-app'
site_description: 'Frontend application documentation'

docs_dir: docs

nav:
  - Home: index.md
  - Development: development.md
  - Components: components.md
  - Testing: testing.md

plugins:
  - techdocs-core
