site_name: 'payment-service'
site_description: 'Payment processing service documentation'

docs_dir: docs

nav:
  - Home: index.md
  - Architecture: architecture.md
  - API Reference: api.md
  - Deployment: deployment.md

plugins:
  - techdocs-core
